[package]
name = "video_importer"
version = "0.5.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
embed-file = "0.2.0"
serde = "1.0.219"
serde_derive = "1.0.219"
serde_json = "1.0.140"

[[bin]]
name = "video_importer"
path = "src/main.rs"
